notifications:
  email: false

sudo: false
dist: trusty

language: c
compiler: gcc

addons:
  apt:
    packages:
      - python-software-properties
      - python-pip

before_install:
  - pip install --user cpp-coveralls

script:
  - make
  - make test

after_success:
  - coveralls -e lib -e test -e debug.c -e debug.h -e main.c --gcov-options '\-lp'

