notifications:
  email: false

dist: xenial

language: c
compiler: gcc

addons:
  apt:
    packages:
      - libidn2-0-dev
      - python-pip
      - python-software-properties

before_install:
  - pip install --user cpp-coveralls

script:
  - make
  - make test

after_success:
  - make coveralls

