#include "config.h"
#include "mutt_options.h"

const char *a = "apple";
const char *b = "banana";
const char *c = "cherry";
const char *d = "damson";
const char *e = "elderberry";
const char *f = "fig";
const char *g = "guava";
const char *h = "hawthorn";
const char *i = "ilama";
const char *j = "jackfruit";
const char *k = "kumquat";
const char *l = "lemon";
const char *m = "mango";
const char *n = "nectarine";
const char *o = "olive";
const char *p = "papaya";
const char *q = "quince";
const char *r = "raspberry";
const char *s = "strawberry";
const char *t = "tangerine";
const char *u = "ugli";
const char *v = "vanilla";
const char *w = "wolfberry";
const char *x = "xigua";
const char *y = "yew";
const char *z = "ziziphus";

#define UL (unsigned long)

#define MIXMASTER "mixmaster"

#define SORT_DATE     1 /* the date the mail was sent. */
#define SORT_SIZE     2
#define SORT_SUBJECT  3
#define SORT_ALPHA    3 /* makedoc.c requires this */
#define SORT_FROM     4
#define SORT_ORDER    5 /* the order the messages appear in the mailbox. */
#define SORT_THREADS  6
#define SORT_RECEIVED 7 /* when the message were delivered locally */
#define SORT_TO       8
#define SORT_SCORE    9
#define SORT_ALIAS    10
#define SORT_ADDRESS  11
#define SORT_KEYID    12
#define SORT_TRUST    13
#define SORT_SPAM     14
#define SORT_COUNT    15
#define SORT_UNREAD   16
#define SORT_FLAGGED  17
#define SORT_PATH     18
#define SORT_LABEL    19
#define SORT_DESC     20

/* supported mailbox formats */
enum
{
  MUTT_MBOX = 1,
  MUTT_MMDF,
  MUTT_MH,
  MUTT_MAILDIR,
  MUTT_NNTP,
  MUTT_IMAP,
  MUTT_NOTMUCH,
  MUTT_POP,
  MUTT_COMPRESSED,
};

/* possible arguments to set_quadoption() */
enum
{
  MUTT_ABORT = -1,
  MUTT_NO,
  MUTT_YES,
  MUTT_ASKNO,
  MUTT_ASKYES
};

struct Option MuttVars[] = {
  { "abort_noattach",                   DT_QUAD,                 MUTT_NO },
  { "abort_nosubject",                  DT_QUAD,                 MUTT_ASKYES },
  { "abort_unmodified",                 DT_QUAD,                 MUTT_YES },
  { "alias_file",                       DT_PATH,                 UL "~/.muttrc" },
  { "alias_format",                     DT_STR,                  UL "%4n %2f %t %-10a   %r" },
  { "allow_8bit",                       DT_BOOL,                 1 },
  { "allow_ansi",                       DT_BOOL,                 0 },
  { "arrow_cursor",                     DT_BOOL,                 0 },
  { "ascii_chars",                      DT_BOOL,                 0 },
  { "askbcc",                           DT_BOOL,                 0 },
  { "askcc",                            DT_BOOL,                 0 },
  { "ask_follow_up",                    DT_BOOL,                 0 },
  { "ask_x_comment_to",                 DT_BOOL,                 0 },
  { "assumed_charset",                  DT_STR,                  0 },
  { "attach_charset",                   DT_STR,                  0 },
  { "attach_format",                    DT_STR,                  UL "%u%D%I %t%4n %T%.40d%> [%.7m/%.10M, %.6e%?C?, %C?, %s] " },
  { "attach_keyword",                   DT_RX,                   UL "\\<(attach|attached|attachments?)\\>" },
  { "attach_sep",                       DT_STR,                  UL "\n" },
  { "attach_split",                     DT_BOOL,                 1 },
  { "attribution",                      DT_STR,                  UL "On %d, %n wrote:" },
  { "attribution_locale",               DT_STR,                  UL "" },
  { "auto_tag",                         DT_BOOL,                 0 },
  { "autoedit",                         DT_BOOL,                 0 },
  { "beep",                             DT_BOOL,                 1 },
  { "beep_new",                         DT_BOOL,                 0 },
  { "bounce",                           DT_QUAD,                 MUTT_ASKYES },
  { "bounce_delivered",                 DT_BOOL,                 1 },
  { "braille_friendly",                 DT_BOOL,                 0 },
  { "catchup_newsgroup",                DT_QUAD,                 MUTT_ASKYES },
  { "certificate_file",                 DT_PATH,                 UL "~/.mutt_certificates" },
  { "charset",                          DT_STR,                  0 },
  { "check_mbox_size",                  DT_BOOL,                 0 },
  { "check_new",                        DT_BOOL,                 1 },
  { "collapse_unread",                  DT_BOOL,                 1 },
  { "collapse_flagged",                 DT_BOOL,                 1 },
  { "compose_format",                   DT_STR,                  UL "-- NeoMutt: Compose  [Approx. msg size: %l   Atts: %a]%>-" },
  { "config_charset",                   DT_STR,                  0 },
  { "confirmappend",                    DT_BOOL,                 1 },
  { "confirmcreate",                    DT_BOOL,                 1 },
  { "connect_timeout",                  DT_NUM,                  30 },
  { "content_type",                     DT_STR,                  UL "text/plain" },
  { "copy",                             DT_QUAD,                 MUTT_YES },
  { "pgp_autoencrypt",                  DT_SYN,                  0 },
  { "crypt_autoencrypt",                DT_BOOL,                 0 },
  { "crypt_autopgp",                    DT_BOOL,                 1 },
  { "pgp_autosign",                     DT_SYN,                  0 },
  { "crypt_autosign",                   DT_BOOL,                 0 },
  { "crypt_autosmime",                  DT_BOOL,                 1 },
  { "crypt_confirmhook",                DT_BOOL,                 1 },
  { "crypt_opportunistic_encrypt",      DT_BOOL,                 0 },
  { "pgp_replyencrypt",                 DT_SYN,                  1  },
  { "crypt_replyencrypt",               DT_BOOL,                 1 },
  { "pgp_replysign",                    DT_SYN,                  0 },
  { "crypt_replysign",                  DT_BOOL,                 0 },
  { "pgp_replysignencrypted",           DT_SYN,                  0 },
  { "crypt_replysignencrypted",         DT_BOOL,                 0 },
  { "crypt_timestamp",                  DT_BOOL,                 1 },
  { "crypt_use_gpgme",                  DT_BOOL,                 0 },
  { "crypt_use_pka",                    DT_BOOL,                 0 },
  { "pgp_verify_sig",                   DT_SYN,                  0 },
  { "crypt_verify_sig",                 DT_QUAD,                 MUTT_YES },
  { "date_format",                      DT_STR,                  UL "!%a, %b %d, %Y at %I:%M:%S%p %Z" },
  { "debug_level",                      DT_NUM,                  0 },
  { "debug_file",                       DT_PATH,                 UL "~/.muttdebug" },
  { "default_hook",                     DT_STR,                  UL "~f %s !~P | (~P ~C %s)" },
  { "delete",                           DT_QUAD,                 MUTT_ASKYES },
  { "delete_untag",                     DT_BOOL,                 1 },
  { "digest_collapse",                  DT_BOOL,                 1 },
  { "display_filter",                   DT_PATH,                 UL "" },
  { "dsn_notify",                       DT_STR,                  UL "" },
  { "dsn_return",                       DT_STR,                  UL "" },
  { "duplicate_threads",                DT_BOOL,                 1 },
  { "edit_headers",                     DT_BOOL,                 0 },
  { "edit_hdrs",                        DT_SYN,                  0 },
  { "editor",                           DT_PATH,                 0 },
  { "empty_subject",                    DT_STR,                  UL "Re: your mail" },
  { "encode_from",                      DT_BOOL,                 0 },
  { "entropy_file",                     DT_PATH,                 0 },
  { "envelope_from_address",            DT_ADDR,                 0 },
  { "escape",                           DT_STR,                  UL "~" },
  { "fast_reply",                       DT_BOOL,                 0 },
  { "fcc_attach",                       DT_QUAD,                 MUTT_YES },
  { "fcc_clear",                        DT_BOOL,                 0 },
  { "flag_safe",                        DT_BOOL,                 0 },
  { "folder",                           DT_PATH,                 UL "~/Mail" },
  { "folder_format",                    DT_STR,                  UL "%2C %t %N %F %2l %-8.8u %-8.8g %8s %d %f" },
  { "followup_to",                      DT_BOOL,                 1 },
  { "followup_to_poster",               DT_QUAD,                 MUTT_ASKYES },
  { "force_name",                       DT_BOOL,                 0 },
  { "forward_attribution_intro",        DT_STR,                  UL "----- Forwarded message from %f -----" },
  { "forward_attribution_trailer",      DT_STR,                  UL "----- End forwarded message -----" },
  { "forward_decode",                   DT_BOOL,                 1 },
  { "forw_decode",                      DT_SYN,                  0 },
  { "forward_decrypt",                  DT_BOOL,                 1 },
  { "forw_decrypt",                     DT_SYN,                  0 },
  { "forward_edit",                     DT_QUAD,                 MUTT_YES },
  { "forward_format",                   DT_STR,                  UL "[%a: %s]" },
  { "forw_format",                      DT_SYN,                  0 },
  { "forward_quote",                    DT_BOOL,                 0 },
  { "forw_quote",                       DT_SYN,                  0 },
  { "forward_references",               DT_BOOL,                 0 },
  { "from",                             DT_ADDR,                 0 },
  { "from_chars",                       DT_MBCHARTBL,            0 },
  { "gecos_mask",                       DT_RX,                   UL "^[^,]*" },
  { "group_index_format",               DT_STR,                  UL "%4C %M%N %5s  %-45.45f %d" },
  { "hdr_format",                       DT_SYN,                  0 },
  { "hdrs",                             DT_BOOL,                 1 },
  { "header",                           DT_BOOL,                 0 },
  { "header_cache",                     DT_PATH,                 0 },
  { "header_cache_backend",             DT_HCACHE,               0 },
  { "header_cache_compress",            DT_BOOL,                 1 },
  { "header_cache_pagesize",            DT_STR,                  UL "16384" },
  { "header_color_partial",             DT_BOOL,                 0 },
  { "help",                             DT_BOOL,                 1 },
  { "hidden_host",                      DT_BOOL,                 0 },
  { "hide_limited",                     DT_BOOL,                 0 },
  { "hide_missing",                     DT_BOOL,                 1 },
  { "hide_thread_subject",              DT_BOOL,                 1 },
  { "hide_top_limited",                 DT_BOOL,                 0 },
  { "hide_top_missing",                 DT_BOOL,                 1 },
  { "history",                          DT_NUM,                  10 },
  { "history_file",                     DT_PATH,                 UL "~/.mutthistory" },
  { "history_remove_dups",              DT_BOOL,                 0 },
  { "honor_disposition",                DT_BOOL,                 0 },
  { "honor_followup_to",                DT_QUAD,                 MUTT_YES },
  { "hostname",                         DT_STR,                  0 },
  { "idn_decode",                       DT_BOOL,                 1 },
  { "idn_encode",                       DT_BOOL,                 1 },
  { "ignore_linear_white_space",        DT_BOOL,                 0 },
  { "ignore_list_reply_to",             DT_BOOL,                 0 },
  { "show_multipart_alternative",       DT_STR,                  0 },
  { "imap_authenticators",              DT_STR,                  0 },
  { "imap_check_subscribed",            DT_BOOL,                 0 },
  { "imap_delim_chars",                 DT_STR,                  UL "/." },
  { "imap_headers",                     DT_STR,                  0 },
  { "imap_idle",                        DT_BOOL,                 0 },
  { "imap_keepalive",                   DT_NUM,                  300 },
  { "imap_list_subscribed",             DT_BOOL,                 0 },
  { "imap_login",                       DT_STR,                  0 },
  { "imap_pass",                        DT_STR,                  0 },
  { "imap_passive",                     DT_BOOL,                 1 },
  { "imap_peek",                        DT_BOOL,                 1 },
  { "imap_pipeline_depth",              DT_NUM,                  15 },
  { "imap_servernoise",                 DT_BOOL,                 1 },
  { "imap_user",                        DT_STR,                  0 },
  { "implicit_autoview",                DT_BOOL,                 0 },
  { "include",                          DT_QUAD,                 MUTT_ASKYES },
  { "include_onlyfirst",                DT_BOOL,                 0 },
  { "indent_string",                    DT_STR,                  UL "> " },
  { "indent_str",                       DT_SYN,                  0 },
  { "index_format",                     DT_STR,                  UL "%4C %Z %{%b %d} %-15.15L (%?l?%4l&%4c?) %s" },
  { "inews",                            DT_PATH,                 UL "" },
  { "ispell",                           DT_PATH,                 UL ISPELL },
  { "keep_flagged",                     DT_BOOL,                 0 },
  { "keywords_legacy",                  DT_BOOL,                 1 },
  { "keywords_standard",                DT_BOOL,                 0 },
  { "mail_check",                       DT_NUM,                  5 },
  { "mail_check_recent",                DT_BOOL,                 1 },
  { "mail_check_stats",                 DT_BOOL,                 0 },
  { "mail_check_stats_interval",        DT_NUM,                  60 },
  { "mailcap_path",                     DT_STR,                  0 },
  { "mailcap_sanitize",                 DT_BOOL,                 1 },
  { "maildir_header_cache_verify",      DT_BOOL,                 1 },
  { "maildir_trash",                    DT_BOOL,                 0 },
  { "maildir_check_cur",                DT_BOOL,                 0 },
  { "mark_macro_prefix",                DT_STR,                  UL "'" },
  { "mark_old",                         DT_BOOL,                 1 },
  { "markers",                          DT_BOOL,                 1 },
  { "mask",                             DT_RX,                   UL "!^\\.[^.]" },
  { "mbox",                             DT_PATH,                 UL "~/mbox" },
  { "mbox_type",                        DT_MAGIC,                MUTT_MBOX },
  { "menu_context",                     DT_NUM,                  0 },
  { "menu_move_off",                    DT_BOOL,                 1 },
  { "menu_scroll",                      DT_BOOL,                 0 },
  { "message_cache_clean",              DT_BOOL,                 0 },
  { "message_cachedir",                 DT_PATH,                 0 },
  { "message_format",                   DT_STR,                  UL "%s" },
  { "msg_format",                       DT_SYN,                  0 },
  { "meta_key",                         DT_BOOL,                 0 },
  { "metoo",                            DT_BOOL,                 0 },
  { "mh_purge",                         DT_BOOL,                 0 },
  { "mh_seq_flagged",                   DT_STR,                  UL "flagged" },
  { "mh_seq_replied",                   DT_STR,                  UL "replied" },
  { "mh_seq_unseen",                    DT_STR,                  UL "unseen" },
  { "mime_forward",                     DT_QUAD,                 MUTT_NO },
  { "mime_forward_decode",              DT_BOOL,                 0 },
  { "mime_fwd",                         DT_SYN,                  0 },
  { "mime_forward_rest",                DT_QUAD,                 MUTT_YES },
  { "mime_subject",                     DT_BOOL,                 1 },
  { "mix_entry_format",                 DT_STR,                  UL "%4n %c %-16s %a" },
  { "mixmaster",                        DT_PATH,                 UL MIXMASTER },
  { "move",                             DT_QUAD,                 MUTT_NO },
  { "narrow_tree",                      DT_BOOL,                 0 },
  { "net_inc",                          DT_NUM,                  10 },
  { "new_mail_command",                 DT_PATH,                 UL NULL },
  { "news_cache_dir",                   DT_PATH,                 UL "~/.mutt" },
  { "news_server",                      DT_STR,                  0 },
  { "newsgroups_charset",               DT_STR,                  UL "utf-8" },
  { "newsrc",                           DT_PATH,                 UL "~/.newsrc" },
  { "nntp_authenticators",              DT_STR,                  0 },
  { "nntp_context",                     DT_NUM,                  1000 },
  { "nntp_listgroup",                   DT_BOOL,                 1 },
  { "nntp_load_description",            DT_BOOL,                 1 },
  { "nntp_user",                        DT_STR,                  UL "" },
  { "nntp_pass",                        DT_STR,                  UL "" },
  { "nntp_poll",                        DT_NUM,                  60 },
  { "nm_open_timeout",                  DT_NUM,                  5 },
  { "nm_default_uri",                   DT_STR,                  0 },
  { "nm_hidden_tags",                   DT_STR,                  UL "unread,draft,flagged,passed,replied,attachment,signed,encrypted" },
  { "nm_exclude_tags",                  DT_STR,                  0 },
  { "nm_unread_tag",                    DT_STR,                  UL "unread" },
  { "nm_db_limit",                      DT_NUM,                  0 },
  { "nm_query_type",                    DT_STR,                  UL "messages" },
  { "nm_record",                        DT_BOOL,                 0 },
  { "nm_record_tags",                   DT_STR,                  0 },
  { "nm_query_window_duration",         DT_NUM,                  0 },
  { "nm_query_window_timebase",         DT_STR,                  UL "week" },
  { "nm_query_window_current_search",   DT_STR,                  UL "" },
  { "nm_query_window_current_position", DT_NUM,                  0 },
  { "pager",                            DT_PATH,                 UL "builtin" },
  { "pager_context",                    DT_NUM,                  0 },
  { "pager_format",                     DT_STR,                  UL "-%Z- %C/%m: %-20.20n   %s%*  -- (%P)" },
  { "pager_index_lines",                DT_NUM,                  0 },
  { "pager_stop",                       DT_BOOL,                 0 },
  { "pgp_auto_decode",                  DT_BOOL,                 0 },
  { "pgp_create_traditional",           DT_SYN,                  0 },
  { "pgp_autoinline",                   DT_BOOL,                 0 },
  { "pgp_check_exit",                   DT_BOOL,                 1 },
  { "pgp_clearsign_command",            DT_STR,                  0 },
  { "pgp_decode_command",               DT_STR,                  0 },
  { "pgp_decrypt_command",              DT_STR,                  0 },
  { "pgp_decryption_okay",              DT_RX,                   0 },
  { "pgp_encrypt_only_command",         DT_STR,                  0 },
  { "pgp_encrypt_sign_command",         DT_STR,                  0 },
  { "pgp_entry_format",                 DT_STR,                  UL "%4n %t%f %4l/0x%k %-4a %2c %u" },
  { "pgp_export_command",               DT_STR,                  0 },
  { "pgp_getkeys_command",              DT_STR,                  0 },
  { "pgp_good_sign",                    DT_RX,                   0 },
  { "pgp_ignore_subkeys",               DT_BOOL,                 1 },
  { "pgp_import_command",               DT_STR,                  0 },
  { "pgp_list_pubring_command",         DT_STR,                  0 },
  { "pgp_list_secring_command",         DT_STR,                  0 },
  { "pgp_long_ids",                     DT_BOOL,                 1 },
  { "pgp_mime_auto",                    DT_QUAD,                 MUTT_ASKYES },
  { "pgp_auto_traditional",             DT_SYN,                  0 },
  { "pgp_replyinline",                  DT_BOOL,                 0 },
  { "pgp_retainable_sigs",              DT_BOOL,                 0 },
  { "pgp_self_encrypt",                 DT_BOOL,                 0 },
  { "pgp_self_encrypt_as",              DT_STR,                  0 },
  { "pgp_show_unusable",                DT_BOOL,                 1 },
  { "pgp_sign_as",                      DT_STR,                  0 },
  { "pgp_sign_command",                 DT_STR,                  0 },
  { "pgp_sort_keys",                    DT_SORT|DT_SORT_KEYS,    SORT_ADDRESS },
  { "pgp_strict_enc",                   DT_BOOL,                 1 },
  { "pgp_timeout",                      DT_NUM,                  300 },
  { "pgp_use_gpg_agent",                DT_BOOL,                 0 },
  { "pgp_verify_command",               DT_STR,                  0 },
  { "pgp_verify_key_command",           DT_STR,                  0 },
  { "pipe_decode",                      DT_BOOL,                 0 },
  { "pipe_sep",                         DT_STR,                  UL "\n" },
  { "pipe_split",                       DT_BOOL,                 0 },
  { "pop_auth_try_all",                 DT_BOOL,                 1 },
  { "pop_authenticators",               DT_STR,                  0 },
  { "pop_checkinterval",                DT_NUM,                  60 },
  { "pop_delete",                       DT_QUAD,                 MUTT_ASKNO },
  { "pop_host",                         DT_STR,                  UL "" },
  { "pop_last",                         DT_BOOL,                 0 },
  { "pop_pass",                         DT_STR,                  UL "" },
  { "pop_reconnect",                    DT_QUAD,                 MUTT_ASKYES },
  { "pop_user",                         DT_STR,                  0 },
  { "post_indent_string",               DT_STR,                  UL "" },
  { "post_indent_str",                  DT_SYN,                  0 },
  { "post_moderated",                   DT_QUAD,                 MUTT_ASKYES },
  { "postpone",                         DT_QUAD,                 MUTT_ASKYES },
  { "postponed",                        DT_PATH,                 UL "~/postponed" },
  { "postpone_encrypt",                 DT_BOOL,                 0 },
  { "postpone_encrypt_as",              DT_STR,                  0 },
  { "preconnect",                       DT_STR,                  0 },
  { "print",                            DT_QUAD,                 MUTT_ASKNO },
  { "print_command",                    DT_PATH,                 UL "lpr" },
  { "print_cmd",                        DT_SYN,                  0 },
  { "print_decode",                     DT_BOOL,                 1 },
  { "print_split",                      DT_BOOL,                 0 },
  { "prompt_after",                     DT_BOOL,                 1 },
  { "query_command",                    DT_PATH,                 UL "" },
  { "query_format",                     DT_STR,                  UL "%4c %t %-25.25a %-25.25n %?e?(%e)?" },
  { "quit",                             DT_QUAD,                 MUTT_YES },
  { "quote_regexp",                     DT_RX,                   UL "^([ \t]*[|>:}#])+" },
  { "read_inc",                         DT_NUM,                  10 },
  { "read_only",                        DT_BOOL,                 0 },
  { "realname",                         DT_STR,                  0 },
  { "recall",                           DT_QUAD,                 MUTT_ASKYES },
  { "record",                           DT_PATH,                 UL "~/sent" },
  { "reflow_space_quotes",              DT_BOOL,                 1 },
  { "reflow_text",                      DT_BOOL,                 1 },
  { "reflow_wrap",                      DT_NUM,                  78 },
  { "reply_regexp",                     DT_RX,                   UL "^(re([\\[0-9\\]+])*|aw):[ \t]*" },
  { "reply_self",                       DT_BOOL,                 0 },
  { "reply_to",                         DT_QUAD,                 MUTT_ASKYES },
  { "reply_with_xorig",                 DT_BOOL,                 0 },
  { "resolve",                          DT_BOOL,                 1 },
  { "resume_draft_files",               DT_BOOL,                 0 },
  { "resume_edited_draft_files",        DT_BOOL,                 1 },
  { "reverse_alias",                    DT_BOOL,                 0 },
  { "reverse_name",                     DT_BOOL,                 0 },
  { "reverse_realname",                 DT_BOOL,                 1 },
  { "rfc2047_parameters",               DT_BOOL,                 0 },
  { "save_address",                     DT_BOOL,                 0 },
  { "save_empty",                       DT_BOOL,                 1 },
  { "save_history",                     DT_NUM,                  0 },
  { "save_name",                        DT_BOOL,                 0 },
  { "score",                            DT_BOOL,                 1 },
  { "score_threshold_delete",           DT_NUM,                  UL -1 },
  { "score_threshold_flag",             DT_NUM,                  9999 },
  { "score_threshold_read",             DT_NUM,                  UL -1 },
  { "search_context",                   DT_NUM,                  0 },
  { "send_charset",                     DT_STR,                  UL "us-ascii:iso-8859-1:utf-8" },
  { "sendmail",                         DT_PATH,                 UL SENDMAIL " -oem -oi" },
  { "sendmail_wait",                    DT_NUM,                  0 },
  { "shell",                            DT_PATH,                 0 },
  { "save_unsubscribed",                DT_BOOL,                 0 },
  { "show_new_news",                    DT_BOOL,                 1 },
  { "show_only_unread",                 DT_BOOL,                 0 },
  { "sidebar_delim_chars",              DT_STR,                  UL "/." },
  { "sidebar_divider_char",             DT_STR,                  0 },
  { "sidebar_folder_indent",            DT_BOOL,                 0 },
  { "sidebar_format",                   DT_STR,                  UL "%B%*  %n" },
  { "sidebar_indent_string",            DT_STR,                  UL "  " },
  { "sidebar_new_mail_only",            DT_BOOL,                 0 },
  { "sidebar_next_new_wrap",            DT_BOOL,                 0 },
  { "sidebar_on_right",                 DT_BOOL,                 0 },
  { "sidebar_short_path",               DT_BOOL,                 0 },
  { "sidebar_sort_method",              DT_SORT|DT_SORT_SIDEBAR, SORT_ORDER },
  { "sidebar_visible",                  DT_BOOL,                 0 },
  { "sidebar_width",                    DT_NUM,                  30 },
  { "sig_dashes",                       DT_BOOL,                 1 },
  { "sig_on_top",                       DT_BOOL,                 0 },
  { "signature",                        DT_PATH,                 UL "~/.signature" },
  { "simple_search",                    DT_STR,                  UL "~f %s | ~s %s" },
  { "skip_quoted_offset",               DT_NUM,                  0 },
  { "sleep_time",                       DT_NUM,                  1 },
  { "smart_wrap",                       DT_BOOL,                 1 },
  { "smileys",                          DT_RX,                   UL "(>From )|(:[-^]?[][)(><}{|/DP])" },
  { "smime_ask_cert_label",             DT_BOOL,                 1 },
  { "smime_ca_location",                DT_PATH,                 0 },
  { "smime_certificates",               DT_PATH,                 0 },
  { "smime_decrypt_command",            DT_STR,                  0 },
  { "smime_decrypt_use_default_key",    DT_BOOL,                 1 },
  { "smime_sign_as",                    DT_SYN,                  0 },
  { "smime_default_key",                DT_STR,                  0 },
  { "smime_encrypt_command",            DT_STR,                  0 },
  { "smime_encrypt_with",               DT_STR,                  UL "aes256" },
  { "smime_get_cert_command",           DT_STR,                  0 },
  { "smime_get_cert_email_command",     DT_STR,                  0 },
  { "smime_get_signer_cert_command",    DT_STR,                  0 },
  { "smime_import_cert_command",        DT_STR,                  0 },
  { "smime_is_default",                 DT_BOOL,                 0 },
  { "smime_keys",                       DT_PATH,                 0 },
  { "smime_pk7out_command",             DT_STR,                  0 },
  { "smime_self_encrypt",               DT_BOOL,                 0 },
  { "smime_self_encrypt_as",            DT_STR,                  0 },
  { "smime_sign_command",               DT_STR,                  0 },
  { "smime_sign_digest_alg",            DT_STR,                  UL "sha256" },
  { "smime_timeout",                    DT_NUM,                  300 },
  { "smime_verify_command",             DT_STR,                  0 },
  { "smime_verify_opaque_command",      DT_STR,                  0 },
  { "smtp_authenticators",              DT_STR,                  0 },
  { "smtp_pass",                        DT_STR,                  0 },
  { "smtp_url",                         DT_STR,                  0 },
  { "sort",                             DT_SORT,                 SORT_DATE },
  { "sort_alias",                       DT_SORT|DT_SORT_ALIAS,   SORT_ALIAS },
  { "sort_aux",                         DT_SORT|DT_SORT_AUX,     SORT_DATE },
  { "sort_browser",                     DT_SORT|DT_SORT_BROWSER, SORT_ALPHA },
  { "sort_re",                          DT_BOOL,                 1 },
  { "spam_separator",                   DT_STR,                  UL "," },
  { "spoolfile",                        DT_PATH,                 0 },
  { "ssl_ca_certificates_file",         DT_PATH,                 0 },
  { "ssl_client_cert",                  DT_PATH,                 0 },
  { "ssl_force_tls",                    DT_BOOL,                 0 },
  { "ssl_min_dh_prime_bits",            DT_NUM,                  0 },
  { "ssl_starttls",                     DT_QUAD,                 MUTT_YES },
  { "ssl_use_sslv2",                    DT_BOOL,                 0 },
  { "ssl_use_sslv3",                    DT_BOOL,                 0 },
  { "ssl_use_tlsv1",                    DT_BOOL,                 1 },
  { "ssl_use_tlsv1_1",                  DT_BOOL,                 1 },
  { "ssl_use_tlsv1_2",                  DT_BOOL,                 1 },
  { "ssl_usesystemcerts",               DT_BOOL,                 1 },
  { "ssl_verify_dates",                 DT_BOOL,                 1 },
  { "ssl_verify_host",                  DT_BOOL,                 1 },
  { "ssl_verify_partial_chains",        DT_BOOL,                 0 },
  { "ssl_ciphers",                      DT_STR,                  0 },
  { "status_chars",                     DT_MBCHARTBL,            UL "-*%A" },
  { "status_format",                    DT_STR,                  UL "-%r-NeoMutt: %f [Msgs:%?M?%M/?%m%?n? New:%n?%?o? Old:%o?%?d? Del:%d?%?F? Flag:%F?%?t? Tag:%t?%?p? Post:%p?%?b? Inc:%b?%?l? %l?]---(%s/%S)-%>-(%P)---" },
  { "status_on_top",                    DT_BOOL,                 0 },
  { "strict_threads",                   DT_BOOL,                 0 },
  { "suspend",                          DT_BOOL,                 1 },
  { "text_flowed",                      DT_BOOL,                 0 },
  { "thorough_search",                  DT_BOOL,                 1 },
  { "thread_received",                  DT_BOOL,                 0 },
  { "tilde",                            DT_BOOL,                 0 },
  { "time_inc",                         DT_NUM,                  0 },
  { "timeout",                          DT_NUM,                  600 },
  { "tmpdir",                           DT_PATH,                 0 },
  { "to_chars",                         DT_MBCHARTBL,            UL " +TCFL" },
  { "flag_chars",                       DT_MBCHARTBL,            UL "*!DdrONon- " },
  { "trash",                            DT_PATH,                 0 },
  { "ts_icon_format",                   DT_STR,                  UL "M%?n?AIL&ail?" },
  { "ts_enabled",                       DT_BOOL,                 0 },
  { "ts_status_format",                 DT_STR,                  UL "NeoMutt with %?m?%m messages&no messages?%?n? [%n NEW]?" },
  { "tunnel",                           DT_STR,                  0 },
  { "uncollapse_jump",                  DT_BOOL,                 0 },
  { "uncollapse_new",                   DT_BOOL,                 1 },
  { "use_8bitmime",                     DT_BOOL,                 0 },
  { "use_domain",                       DT_BOOL,                 1 },
  { "use_envelope_from",                DT_BOOL,                 0 },
  { "envelope_from",                    DT_SYN,                  0 },
  { "use_from",                         DT_BOOL,                 1 },
  { "use_ipv6",                         DT_BOOL,                 1 },
  { "user_agent",                       DT_BOOL,                 1 },
  { "visual",                           DT_PATH,                 0 },
  { "vfolder_format",                   DT_STR,                  UL "%2C %?n?%4n/&     ?%4m %f" },
  { "virtual_spoolfile",                DT_BOOL,                 0 },
  { "wait_key",                         DT_BOOL,                 1 },
  { "weed",                             DT_BOOL,                 1 },
  { "wrap",                             DT_NUM,                  0 },
  { "wrap_headers",                     DT_NUM,                  78 },
  { "wrap_search",                      DT_BOOL,                 1 },
  { "wrapmargin",                       DT_NUM,                  0 },
  { "write_bcc",                        DT_BOOL,                 1 },
  { "write_inc",                        DT_NUM,                  10 },
  { "xterm_icon",                       DT_SYN,                  0 },
  { "xterm_title",                      DT_SYN,                  0 },
  { "xterm_set_titles",                 DT_SYN,                  0 },
  { "xlabel_delimiter",                 DT_STR,                  UL "" },
  { "x_comment_to",                     DT_BOOL,                 0 },
  { "collapse_all",                     DT_BOOL,                 0 },
  { "pgp_encrypt_self",                 DT_QUAD,                 MUTT_NO },
  { "smime_encrypt_self",               DT_QUAD,                 MUTT_NO },
  { NULL,                               0,                       0 },
};

